channel: '#YOUR_SLACK_CHANNEL'
token: 'YOUR_SLACK_TOKEN'
persons:
  - '@YOUR_NAME'
  - '@YOUR_FRIENDS_NAME1'
  - '@YOUR_FRIENDS_NAME2'
gomitypes:
  sunday:
   default:
  monday:
    default: '燃える'
  tuesday:
   default:
  wednesday:
    default: 'ビン缶・ペットボトル・段ボール'
  thursdy:
    default: '燃える'
  friday:
    default:
    2week: '不燃'
    4week: '不燃'
  saturday:
    default: